name: Lint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v6
      - name: Install GO
        uses: actions/setup-go@v6
        with:
          go-version: '1.23'
          cache: 'true'
      - run: go version
      - name: Install deps
        run: go mod download
      - name: Lint
        run: make lint